export const getChallenges = (state) => [
  {
    id: 'tap10',
    title: 'Зробити 10 кліків',
    description: 'Натисни на ігровий об’єкт 10 разів.',
    progress: `${state.tapCount}/10`,
    done: state.tapCount >= 10,
  },
  {
    id: 'double5',
    title: 'Зробити подвійний клік 5 разів',
    description: 'Виконай подвійне натискання по об’єкту 5 разів.',
    progress: `${state.doubleTapCount}/5`,
    done: state.doubleTapCount >= 5,
  },
  {
    id: 'longpress',
    title: 'Утримувати об’єкт 3 секунди',
    description: 'Натисни на об’єкт і потримай його 3 секунди.',
    progress: state.longPressDone ? '1/1' : '0/1',
    done: state.longPressDone,
  },
  {
    id: 'drag',
    title: 'Перетягнути об’єкт',
    description: 'Перемісти ігровий об’єкт по екрану.',
    progress: state.dragDone ? '1/1' : '0/1',
    done: state.dragDone,
  },
  {
    id: 'swipeRight',
    title: 'Зробити свайп вправо',
    description: 'Проведи по об’єкту вправо.',
    progress: state.swipeRightDone ? '1/1' : '0/1',
    done: state.swipeRightDone,
  },
  {
    id: 'swipeLeft',
    title: 'Зробити свайп вліво',
    description: 'Проведи по об’єкту вліво.',
    progress: state.swipeLeftDone ? '1/1' : '0/1',
    done: state.swipeLeftDone,
  },
  {
    id: 'pinch',
    title: 'Змінити розмір об’єкта',
    description: 'Використай pinch-жест для зміни розміру.',
    progress: state.pinchDone ? '1/1' : '0/1',
    done: state.pinchDone,
  },
  {
    id: 'score100',
    title: 'Отримати 100 очок',
    description: 'Набери 100 очок будь-якими жестами.',
    progress: `${state.score}/100`,
    done: state.score >= 100,
  },
  {
    id: 'custom',
    title: 'Виконати бонусне завдання',
    description: 'Натиснути кнопку бонусного завдання на головному екрані або в налаштуваннях.',
    progress: state.customTaskDone ? '1/1' : '0/1',
    done: state.customTaskDone,
  },
];
